# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EavesdropIT Podcasts from Ops to Dev with a sprinkle of devops

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Podcasts

description: > # this means to ignore newlines until "baseurl:"
  Simple Jekyll theme to host internal/external events happening in and around your area. Free free to contribute or fork the repo.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eavesdropit.github.io" # the base hostname & protocol for your site

#These settings might be able to go?
author: Niklas Akerlund
twitter_username: eavesdrop_it
github_username:  eavesdropit/vniklas
company_name: EavesDropIT

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

